# Generated by Django 4.1.7 on 2023-02-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('author', models.CharField(default='Author', max_length=40, verbose_name='Author')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Crated at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
