# Generated by Django 4.1.7 on 2023-02-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(blank=True, default='john_doe@mail.com', max_length=40, null=True, verbose_name='john_doe@mail.com'),
        ),
    ]
